### ISSUE TITLE
Column headings don't align with values

### ISSUE THREAD

**Issue by LeaseOnLife** [Rodemfr/meteovache_pi#12]
This is on a Linux, Debian bookworm, see screenshot. 
![Screenshot_20230415_102511](https://user-images.githubusercontent.com/919044/232251884-a17a89f1-7ef9-4624-b5d6-c19a0365e4e5.png)

**Comment by Rodemfr** [comment]
With newer OpenCPN versions, the font used is no more "monospace" while it is expected by the plugin, leading to this mismatch.
Thanks for the feedback.

**Comment by LeaseOnLife** [comment]
fixed for me in branch "switch_to_managed_plugin" with commits as of 4/16/2023
