### ISSUE TITLE
http://meteovache.dyndns.org/ server dead

### ISSUE THREAD

**Issue by LeaseOnLife** [Rodemfr/meteovache_pi#22]
see also https://www.cruisersforum.com/forums/f134/migrating-meteovache_pi-to-managed-plugin-scheme-274843-5.html#post3773779

**Comment by Rodemfr** [comment]
The server is up and running but it is behind my internet box which has obvioulsy an issue. Sine I'm on vacation, I cannot access the box and fix the problem. It will be hopefully done tomorrow. This raises a wider problem of relocating the server in a "safer" place on the net for free...
