### ISSUE TITLE
SelEction of a zone instead of a point.

### ISSUE THREAD

**Issue by propedeutique56** [Rodemfr/meteovache_pi#28]
Hi,
First thanks for thhis nice plugin.
But as in zygrib or xgrib, would it be possible to select a zone instead of just a point : when sailing, wee move from one place to another one!
And also, it would be useful to be able to select the same zone automatically, at will (which zygrib nor xgrib do).
Bye

**Comment by Rodemfr** [comment]
Unfortunately, this is not in the "scope" of meteovache_pi. Meteovache_pi try to keeps the amount of data as small as possible to allow getting weather forecast even in very degraded/low bandwidth communication situation. Downloading a full grib file is not possible in this situation.
However, The coming version of OpenCPN/grib_pi will provide a GUI to easily download gribs from Xygrib servers. It is already available on the master branch of the GitHUB and will be available for the coming OCPN 5.10.
